nav_manager_settings:
  CostMap_topic: "/move_base/local_costmap/costmap"
  UpdateTarget_Fps: 5.0
  RobotWidth: 0.5
  TimeResidualMax: 1.0
  WorldFrame: "map"
  BodyFrame: "base_link"
  LookAhead_X: 1.0
  CmdTopic: "/cmd_vel"
  IfTimeInsteadOfConstantXAhead: true
  LookAhead_Time: 1.0
  CmdPub_Fps: 10.0
  SpinnerThread: 5